### PR TITLE
Add ability to set eeprom values

### PR DESCRIPTION
**Pull request by Amanita-muscaria**
Added functionality to set specific EEPROM values. This also re-exports the `ftdi_eeprom_value` type.

### CODE REVIEW

**Comment by cr1901** [comment]
Thank you for your PR. Please note this crate is deprecated, but since I keep forgetting to mark it as read-only, it's not fair to you to reject this PR.

**Comment by Amanita-muscaria** [comment]
Is there another FTDI crate I should be using?

**Comment by cr1901** [comment]
I would use [ftdi-rs](https://github.com/tanriol/ftdi-rs), This crate has more of a safe API implemented, but my intent is to get most of the code here into that crate as well. Both crates have the same idea, but I don't want to maintain these bindings.

**Comment by Amanita-muscaria** [comment]
Fair enough. Thanks!

**Pull request merged**
